patch bug in provisioner

diff --git a/packages/provisioner b/packages/provisioner
--- a/packages/provisioner
+++ b/packages/provisioner
@@ -8,7 +8,7 @@ source /etc/os-release
 gitsource() {
   script=${1:-default.sh}
   gitsurl="https://raw.githubusercontent.com/silverelitez-${domain}/deploy/master/${script}"
-  source <(curl -s ${gitsurl} | sed 's/^404:.*/echo 404 error - ${gitsurl}/g' | sed 's/^400:.*/echo 400 error - ${gitsurl}/g' | dos2unix || echo echo Error) ${2}
+  source <(curl -s ${gitsurl} | sed 's/^404:.*/echo 404 error - ${gitsurl}/g' | sed 's/^400:.*/echo 400 error - ${gitsurl}/g' || echo echo Error) ${2}
 }
 is_sudo() {
   echo -n Check for sudo...
@@ -57,9 +57,8 @@ EOL
   echo "Install packages..."
   [ "${ID}" == "gentoo" ] && { echo "Syncing emerge..."; rm "/usr/portage/metadata/timestamp.x"; emerge-webrsync; echo "=sys-auth/realmd-0.16.2 ~amd64" > /etc/portage/package.accept_keywords; eselect profile set default/linux/amd64/17.0; cd; git clone https://anongit.gentoo.org/git/proj/portage.git; sudo eselect python set 1; sudo USE='-filecaps internal-glib' portage/bin/emerge world -NDuv; sudo PYTHON_TARGETS="python2_7" portage/bin/emerge portage -v; }
   [ -e "/etc/yum.repos.d/epel.repo" ] || q_install epel-release
-  q_install dos2unix realmd
-  q_install applydeltarpm deltarpm
-  ${P_INSTALL} nspr yum-utils *bash-complet* kernel-devel
+  q_install applydeltarpm deltarpm dos2unix realmd
+  ${P_INSTALL} nspr yum-utils *bash-complet* kernel-devel dos2unix
   service dbus restart
   systemctl restart systemd-logind
   [ "${ID}" == 'gentoo' ] && { echo -e 'y\n' | layman -a sabayon; emerge realmd --quiet; } || { q_install realm realmd; q_install kinit krb5-workstation; }
@@ -81,7 +80,7 @@ EOL
 }
 _preinstall() {
   echo "Update packager..."
-  [[ ${ID} == 'centos' ]] && { echo "Install delta-rpm etc..."; ${P_INSTALL} tmux yum-utils krb5-workstation deltarpm; }
+  [[ ${ID} == 'centos' ]] && { echo "Install delta-rpm etc..."; ${P_INSTALL} tmux yum-utils krb5-workstation deltarpm; yum makecache fast; }
   [[ ${ID} == 'centos' ]] && { echo "Remove PackageKit-command-not-found..."; ${P_REMOVE} -y PackageKit-command-not-found; }
   P_UPDATE
   [[ ${ID} == 'centos' ]] && { yum-complete-transaction --cleanup-only; yum makecache; }
@@ -94,7 +93,7 @@ _preinstall() {
 
   echo "Update global profile.d script on ${domain}..."
   giturl="https://raw.githubusercontent.com/silverelitez-${domain}/deploy/master/scripts/profile.d/global.sh"
-  curl -s ${giturl} | dos2unix > /etc/profile.d/global.sh
+  curl -s ${giturl} > /etc/profile.d/global.sh
   chown root.root /etc/profile.d/global.sh
   chmod a+x /etc/profile.d/global.sh
   sleep 1
